name: 'Last workflow run status'
description: 'Get the status of the last workflow job'
inputs:
  workflow-id:
    description: 'The ID of the workflow to check. Defaults to the current one'
    required: false

outputs:
  status:
    description: "Status of the previous workflow run"
    value: ${{ steps.lastrun.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Get previous job's status
      uses: actions/github-script@v6
      if: ${{ success() }}
      id: lastrun
      with:
        script: |
            const run_id = ${{ github.run_id }};
            const owner = "${{ github.repository_owner }}";
            const repo = "${{ github.event.repository.name }}";
            const { workflow_id } = (await github.rest.actions.getWorkflowRun({owner, repo, run_id})).data;
            const isLastFailedRun = (await github.rest.actions.listWorkflowRuns({owner, repo, workflow_id: "${{ inputs.workflow-id }}" || workflow_id, per_page: 1, status: "completed"})).data.workflow_runs.filter(run => run.conclusion === "failure").length > 0;
            const message = isLastFailedRun ? "failed" : "succeeded";
            
            console.log(`The last workflow run ${message}`);
            return message;
