name: 'Last workflow run status'
description: 'Get the status of the last workflow job'
inputs:
  workflow-id:
    description: 'The ID of the workflow to check'
    required: true

outputs:
  status:
    description: "Status of the previous workflow run"
    value: ${{ steps.lastrun.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Get previous job's status
      uses: actions/github-script@v6
      if: ${{ success() }}
      id: lastrun
      with:
        script: |
            const workflow_id = ${{ inputs.workflow-id }};
            const isLastFailedRun = (await github.rest.actions.listWorkflowRuns({owner: ${{ github.repository_owner }}, repo: ${{ github.repository }}, workflow_id, per_page: 1, status: "completed"})).data.workflow_runs.filter(run => run.conclusion === "failure").length > 0;
            const message = isLastFailedRun ? "failed" : "succeeded";
            console.log(`The last workflow run ${message}`);
            return message;